routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * WEB
 */

Route::get('/', 'Web\HomeController@index')->name('web.index');
Route::get('/referred/{code}', 'Web\UserController@referred')->name('web.referred');

Route::group(['middleware' => ['auth', 'notifications', 'CVChecked']], function () {


    Route::get('/home', 'Web\HomeController@home')->name('web.home');
    Route::get('/suscription/{plan}/checkout', 'Web\SuscriptionControllers@checkout')->name('web.suscription.checkout')->middleware('verified');;
    Route::get('/suscription/{plan}/finish', 'Web\SuscriptionControllers@checkoutFinish')->name('web.suscription.finish')->middleware('verified');;

    //Route::get('/notifications/add', 'Web\NotificationsControllers@add')->name('web.notifications.add');

    /*
     * Events
     */
    Route::get('/events/{event?}', 'Web\EventsControllers@event')->name('web.events');
    Route::get('/category', function (){
        return view('web.category-page');
    });
    /*
     * Profile
     */
    Route::get('/profile/{user}', 'Web\UserController@profile')->name('web.profile')->middleware('verified');
    Route::post('/profile/cv/store', 'Web\CVController@store')->name('web.profile.cv.store')->middleware('verified');
    Route::post('/profile/cv/additem', 'Web\CVController@addItem')->name('web.profile.cv.additem')->middleware('verified');
    //Route::match(['get', 'post'], '/profile/cv/additem', 'Web\CVController@addItem')->middleware('verified');


    Route::get('/profile/cv/delete/{fromTable}/{item}', 'Web\CVController@deleteItem')->name('web.profile.cv.deleteitem')->middleware('verified');
    Route::post('/profile/avatar/update', 'Web\CVController@avatarUpdate')->name('web.profile.avatar.update')->middleware('verified');

    /*
     * Search
     */
    Route::get('/search/{subcategory?}', 'Web\SearchController@index')->name('web.search')->middleware('verified');;
    Route::get('/home/search', 'Web\SearchController@homeSearch')->name('web.home.search')->middleware('verified');;
    //Route::get('/search/get', 'Web\SearchController@search')->name('web.search.get');
    Route::get('/search/subcategories/{id}', 'Web\SearchController@subcategories')->name('web.search.subcategories')->middleware('verified');;

});

/*
 * ADMIN
 */
Route::group(['middleware' => ['auth', 'role:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/email', function (){
        return view('web.email.verify');
    });

    Route::get('/dashboard', 'Admin\HomeController@index')->name('dashboard');

    Route::resource('users', 'Admin\UsersController');

    Route::resource('events', 'Admin\EventsController',['only' => ['index', 'store', 'create', 'update', 'show', 'edit']]);
    Route::get('events/destroy/{id}', 'Admin\EventsController@destroy')->name('events.destroy');

    Route::resource('categories', 'Admin\CategoriesController',['only' => ['index', 'store', 'create', 'update', 'show', 'edit']]);
    Route::get('categories/destroy/{id}', 'Admin\CategoriesController@destroy')->name('categories.destroy');

    Route::resource('subcategories', 'Admin\SubCategoriesController',['only' => ['index', 'store', 'create', 'update', 'show', 'edit']]);
    Route::get('subcategories/destroy/{id}', 'Admin\SubCategoriesController@destroy')->name('subcategories.destroy');;

    Route::resource('memberships', 'Admin\MembershipsController');

    Route::resource('plans', 'Admin\PlansController');

    Route::resource('reviews', 'Admin\ReviewsController',['only' => ['index', 'store', 'create', 'update', 'show', 'edit']]);
    Route::get('reviews/destroy/{id}', 'Admin\ReviewsController@destroy')->name('reviews.destroy');

    /*Route::get('users', function () {
        // Matches The "/admin/users" URL
    });*/
});




Route::group([/*'middleware' => ['auth', 'role:admin'], */'prefix' => 'admin', 'as' => 'admin.'], function () {





});







/**
 * DESIGN
 */

/*Route::get('/', function (){
   return view('web.landing');
})->name('web');;*/

/*   return view('web.home');
});*/


/*Route::get('/home', function (){
    return view('web.landing');
 })->name('web.landing');*/

/*Route::get('/search', function (){
    return view('web.search');
})->name('web.search');*/

/**
 * EVENTOS
 */
Route::get('/eventos', function (){
    return view('web.eventos');
})->name('web.eventos');


/*
 * ORGANIZADOR
 */
/*Route::get('/organizador', function (){
    return view('web.organizador');
})->name('web.organizador');*/


//Auth::routes();

Auth::routes(['verify' => true]);

Route::get('/register/{role?}', 'Auth\RegisterController@showRegistrationForm')
    ->name('register');

Route::get('/login/{provider}', 'Auth\LoginController@redirectToProvider')
    ->name('social.login');
Route::get('/login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')
    ->name('social.callback');



/*Route::get('/', 'HomeController@index')->name('home');*/

/*Route::get('/search-category', function (){
    return view('web.category-page');
});*/

Route::get('/preguntas-frecuentes', function (){
    return view('web.preguntas');
})->name('web.preguntas');


/*Route::get('/checkout', function (){
    return view('web.checkout');
})->name('web.checkout');*/

app/Http/Controllers/Admin/SubCategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Categories;
use App\Http\Controllers\Controller;
use App\SubCategories;
use Illuminate\Http\Request;

class SubCategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subcategories = SubCategories::with('category');

        if (request()->ajax()) {
            return datatables()->of($subcategories)
                ->addColumn('action', function($row){
                    $btn = '<a href="'.route('admin.subcategories.edit', $row->id).'" data-toggle="tooltip"  data-original-title="Editar" class="edit btn btn-primary btn-sm editItem">Editar</a>';

                    $btn = $btn.' <a href="javascript:void(0)" data-toggle="tooltip" data-original-title="Eliminar" class="btn btn-danger btn-sm deleteItem">Eliminar</a>';
                    return $btn;
                })
                ->rawColumns(['action'])
                ->addIndexColumn()
                ->make(true);
        }

        return view('admin.subcategories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Categories::pluck('category', 'id');

        return view('admin.subcategories.form', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $subcategory = SubCategories::create($request->all());

        return redirect()->route('admin.subcategories.index')->with('success', 'Registro creado correctamente');;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Categories::pluck('category', 'id');
        $subcategory = SubCategories::find($id);

        return view('admin.subcategories.form', compact('subcategory', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $subcategory = SubCategories::find($id);
        $subcategory->category_id = $request->category_id;
        $subcategory->subcategory = $request->subcategory;
        $subcategory->save();

        return redirect()->route('admin.subcategories.index')->with('success', 'Registro actualizado correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/subcategories/form.blade.php
@extends('admin.templates.layout')
@section('content')
    <div class="row">
        <div class="col-12 col-md-12 col-lg-12">
            <div class="card">
                @isset($subcategory)
                    {!! Form::model($subcategory, ['route' => ['admin.subcategories.update', $subcategory->id], 'method' => 'put']) !!}
                    <div class="card-header">
                        <h4>Editar subcategoría</h4>
                    </div>
                @else
                    {!! Form::open(['route' => 'admin.subcategories.store', 'method' => 'post']) !!}
                    <div class="card-header">
                        <h4>Crear subcategoría</h4>
                    </div>
                @endisset

                <div class="card-body">
                    <div class="form-row">

                        <div class="form-group col-md-4">
                            <label for="name">Categoría</label>
                            {!! Form::select('category_id', $categories , old('category_id') , ['class' => 'form-control', 'placeholder' => 'Elige la categoría']) !!}
                            @error('category_id')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group col-md-4">
                            <label for="name">SubCategoría</label>
                            {!! Form::text('subcategory', old('subcategory'), ['class' => ($errors->has('subcategory')) ? 'form-control is-invalid' : 'form-control' ]) !!}
                            @error('subcategory')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="{{ route('admin.subcategories.index') }}" class="btn btn-secondary">Volver</a>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/subcategories/index.blade.php
@extends('admin.templates.layout')
@section('head')
    {{-- DataTable --}}
    <link href="https://cdn.datatables.net/1.10.17/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection
@section('content')
    <div class="row">
        <div class="col-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4>SubCategorias</h4>
                    <div class="card-header-form">
                        <form>
                            <div class="input-group">
                                <div class="input-group-btn">
                                    <a href="{{ route('admin.subcategories.create') }}" class="btn btn-primary"><i
                                                class="fas fa-plus"> Crear</i>
                                    </a>
                                </div>
                                &nbsp;
                                <input type="text" class="form-control" placeholder="Search">
                                <div class="input-group-btn">
                                    <button class="btn btn-primary"><i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="card-body p-3">
                    <div class="table-responsive">
                        {{--<input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input">
                        <span class="custom-switch-indicator"></span>--}}
                        <table class="table table-striped data-table">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Categoría</th>
                                <th>Subcategoría</th>
                                <th>Creado</th>
                                <th>Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <!-- Page Specific JS File -->
{{--<script src="/assets/bundles/apexcharts/apexcharts.min.js"></script>

    <!-- Template JS File -->
    <script src="/assets/js/scripts.js"></script>
    <!-- Custom JS File -->
    <script src="/assets/js/custom.js"></script>--}}
    <script src="/admin/assets/js/page/forms-advanced-forms.js"></script>

 {{--DataTable--}}

    <script src="https://cdn.datatables.net/1.10.17/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script>

        $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var table = $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('admin.subcategories.index') }}",
                language: {
                    url:      "/admin/assets/json/DataTableSpanish.json",
                },
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'category.category', name: 'category.category'},
                    {data: 'subcategory', name: 'subcategory'},
                    {data: 'created_at', name: 'created_at'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            })
        })

    </script>
@endsection