routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * WEB
 */

Route::get('/', 'Web\HomeController@index')->name('web.index');
Route::get('/referred/{code}', 'Web\UserController@referred')->name('web.referred');

Route::group(['middleware' => ['auth', 'notifications', 'CVChecked']], function () {


    Route::get('/home', 'Web\HomeController@home')->name('web.home');
    Route::get('/suscription/{plan}/checkout', 'Web\SuscriptionControllers@checkout')->name('web.suscription.checkout')->middleware('verified');;
    Route::get('/suscription/{plan}/finish', 'Web\SuscriptionControllers@checkoutFinish')->name('web.suscription.finish')->middleware('verified');;

    //Route::get('/notifications/add', 'Web\NotificationsControllers@add')->name('web.notifications.add');

    /*
     * Events
     */
    Route::get('/events/{event?}', 'Web\EventsControllers@event')->name('web.events');
    Route::get('/category', function (){
        return view('web.category-page');
    });
    /*
     * Profile
     */
    Route::get('/profile/{user}', 'Web\UserController@profile')->name('web.profile')->middleware('verified');
    Route::post('/profile/cv/store', 'Web\CVController@store')->name('web.profile.cv.store')->middleware('verified');
    Route::post('/profile/cv/additem', 'Web\CVController@addItem')->name('web.profile.cv.additem')->middleware('verified');
    //Route::match(['get', 'post'], '/profile/cv/additem', 'Web\CVController@addItem')->middleware('verified');


    Route::get('/profile/cv/delete/{fromTable}/{item}', 'Web\CVController@deleteItem')->name('web.profile.cv.deleteitem')->middleware('verified');
    Route::post('/profile/avatar/update', 'Web\CVController@avatarUpdate')->name('web.profile.avatar.update')->middleware('verified');

    /*
     * Search
     */
    Route::get('/search/{subcategory?}', 'Web\SearchController@index')->name('web.search')->middleware('verified');;
    Route::get('/home/search', 'Web\SearchController@homeSearch')->name('web.home.search')->middleware('verified');;
    //Route::get('/search/get', 'Web\SearchController@search')->name('web.search.get');
    Route::get('/search/subcategories/{id}', 'Web\SearchController@subcategories')->name('web.search.subcategories')->middleware('verified');;

});

/*
 * ADMIN
 */
Route::group(['middleware' => ['auth', 'role:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/email', function (){
        return view('web.email.verify');
    });

    Route::get('/dashboard', 'Admin\HomeController@index')->name('dashboard');

    Route::resource('users', 'Admin\UsersController');

    Route::resource('events', 'Admin\EventsController',['only' => ['index', 'store', 'create', 'update', 'show', 'edit']]);
    Route::get('events/destroy/{id}', 'Admin\EventsController@destroy')->name('events.destroy');

    Route::resource('categories', 'Admin\CategoriesController',['only' => ['index', 'store', 'create', 'update', 'show', 'edit']]);
    Route::get('categories/destroy/{id}', 'Admin\CategoriesController@destroy')->name('categories.destroy');

    Route::resource('subcategories', 'Admin\SubCategoriesController',['only' => ['index', 'store', 'create', 'update', 'show', 'edit']]);
    Route::get('subcategories/destroy/{id}', 'Admin\SubCategoriesController@destroy')->name('subcategories.destroy');;

    Route::resource('memberships', 'Admin\MembershipsController');

    Route::resource('plans', 'Admin\PlansController');

    Route::resource('reviews', 'Admin\ReviewsController',['only' => ['index', 'store', 'create', 'update', 'show', 'edit']]);
    Route::get('reviews/destroy/{id}', 'Admin\ReviewsController@destroy')->name('reviews.destroy');

    /*Route::get('users', function () {
        // Matches The "/admin/users" URL
    });*/
});




Route::group([/*'middleware' => ['auth', 'role:admin'], */'prefix' => 'admin', 'as' => 'admin.'], function () {





});







/**
 * DESIGN
 */

/*Route::get('/', function (){
   return view('web.landing');
})->name('web');;*/

/*   return view('web.home');
});*/


/*Route::get('/home', function (){
    return view('web.landing');
 })->name('web.landing');*/

/*Route::get('/search', function (){
    return view('web.search');
})->name('web.search');*/

/**
 * EVENTOS
 */
Route::get('/eventos', function (){
    return view('web.eventos');
})->name('web.eventos');


/*
 * ORGANIZADOR
 */
/*Route::get('/organizador', function (){
    return view('web.organizador');
})->name('web.organizador');*/


//Auth::routes();

Auth::routes(['verify' => true]);

Route::get('/register/{role?}', 'Auth\RegisterController@showRegistrationForm')
    ->name('register');

Route::get('/login/{provider}', 'Auth\LoginController@redirectToProvider')
    ->name('social.login');
Route::get('/login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')
    ->name('social.callback');



/*Route::get('/', 'HomeController@index')->name('home');*/

/*Route::get('/search-category', function (){
    return view('web.category-page');
});*/

Route::get('/preguntas-frecuentes', function (){
    return view('web.preguntas');
})->name('web.preguntas');


/*Route::get('/checkout', function (){
    return view('web.checkout');
})->name('web.checkout');*/

app/Http/Controllers/Web/CVController.php
<?php

namespace App\Http\Controllers\Web;

use App\CVAcademicInformation;
use App\CVInformation;
use App\CVSkills;
use App\CVLanguages;
use App\CVWorkExperience;
use App\Helpers\Message;
use App\Http\Controllers\Controller;
use App\User;
use App\UserDays;
use App\UserFiles;
use App\UserInformation;
use App\UserRatings;
use App\UserReviews;
use App\UserServices;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;

class CVController extends Controller
{
    public function store(Request $request)
    {
        //dd($request->all());
        try {
            DB::beginTransaction();
            $userinfo = UserInformation::where('user_id', Auth::id())->first();
            $userinfo->latitud          = $request->latitud;
            $userinfo->longitud         = $request->longitud;
            $userinfo->city_name        = $request->city_name;
            $userinfo->city_place_id    = $request->city_place_id;
            $userinfo->save();

            $cvinformation = CVInformation::firstOrNew(['user_id' => Auth::id()]);
            $cvinformation->about           = $request->about;
            $cvinformation->subcategory_id  = $request->subcategory_id_main;
            $cvinformation->work_status     = $request->work_status;
            $cvinformation->user_id         = Auth::id();
            $cvinformation->save();

            if (!$request->work_status){
                $workexperience = new CVWorkExperience();
                $workexperience->business       = $request->business;
                $workexperience->current_work   = $request->current_work ? 1 : 0;
                $workexperience->antiquity      = $request->antiquity;
                $workexperience->user_id        = Auth::id();
                $workexperience->save();
            }

            foreach ($request->service as $key => $service) {
                if ($service != null){
                    $services = new UserServices();
                    $services->subcategory_id   = $request->subcategory_id[$key];
                    $services->service          = $service;
                    $services->price_from       = $request->price_from[$key];
                    $services->price_to         = $request->price_to[$key];
                    $services->user_id          = Auth::id();;
                    $services->save();
                }
            }

            foreach ($request->institution as $key => $item) {
                if ($item != null){
                    $academic = new CVAcademicInformation();
                    $academic->institution  = $item;
                    $academic->from_year    = $request->from_year[$key];
                    $academic->to_year      = $request->to_year[$key];
                    $academic->title        = $request->title[$key];
                    $academic->user_id      = Auth::id();
                    $academic->save();
                }
            }

            foreach ($request->day as $key => $day) {
                if ($day != null) {
                    $userdays = new UserDays();
                    $userdays->user_id = Auth::id();
                    $userdays->day_id = $day;
                    $userdays->hour_from = $request->hour_from[$key];
                    $userdays->hour_to = $request->hour_to[$key];
                    $userdays->save();
                }
            }

            DB::commit();

            return redirect()->back()->with('notifications', Message::message('Correcto', 'Información guardada correctamente', 'success'));
        }catch (\Exception $e){
            DB::rollBack();
            Log::info('CV STORE MSG'.$e->getMessage());
            //dd('A');

            return redirect()->back()->with('notifications', Message::message('No se pudieron almacenar los datos', 'Por favor, intente más tarde', 'warning'));
        }

        //return redirect()->back()->with('success', 'Datos guardados correctamente');
    }

    public function addItem(Request $request)
    {

        switch ($request->data_from){
            case 'cva': // User Avatar
                //dd($request->file('user_avatar'));
                //dd($request->user_avatar);
                $user = User::find(Auth::id());

                if($request->hasFile('user_avatar')){
                    if (Storage::exists('public/users-avatar/'.$user->avatar)){
                        Storage::delete('public/users-avatar/'.$user->avatar);
                    }
                    if (Storage::exists('public/users-avatar/'.$user->avatar_thumb)){
                        Storage::delete('public/users-avatar/'.$user->avatar_thumb);
                    }

                    $file_name = Str::uuid().'.jpg';
                    //dd($file_name);

                    $request->user_avatar->storeAs('public/users-avatar',$file_name);

                    Image::make($request->file('user_avatar'))
                        ->resize('400','400')
                        ->save(public_path('storage').'/users-avatar/'.'thumb_'.$file_name);

                    $user->avatar = $file_name;
                    $user->avatar_thumb = 'thumb_'.$file_name;
                    $user->save();
                }

                break;
            case 'cvi': // User Information

                $user = User::find(Auth::id());
                if ($request->name){
                    $user->name = $request->name;
                }
                $user->save();

                $information = CVInformation::where('user_id', Auth::id())->first();

                if ($request->about){
                    $information->about             = $request->about;
                }

                if ($request->subcategory_id_main){
                    $information->subcategory_id    = $request->subcategory_id_main;
                }

                $information->user_id           = Auth::id();
                $information->save();

                break;
            case 'cvai': //CV Academic Information
                $acainformation = new CVAcademicInformation();
                $acainformation->title          = $request->title;
                $acainformation->institution    = $request->institution;
                $acainformation->from_year      = $request->from_year;
                $acainformation->to_year      = $request->to_year;
                //$acainformation->from_date      = $request->from_date;
                //$acainformation->to_date        = $request->to_date;
                $acainformation->status         = $request->status;
                $acainformation->user_id        = Auth::id();
                $acainformation->save();

                break;

            case 'cvwe': //CV Work Experience

                $workexp = new CVWorkExperience();
                //$workexp->position    = $request->position;
                $workexp->business      = $request->business;
                $workexp->antiquity     = $request->antiquity;
                $workexp->current_work  = $request->current_work == 'true' ? 1 : 0;
                //$workexp->from_date   = $request->from_date;
                //$workexp->to_date     = $request->to_date;
                $workexp->user_id       = Auth::id();
                $workexp->save();

                break;

            case 'cvs': //CV Skills
                $skill = new CVSkills();
                $skill->skill           = $request->skill;
                $skill->percent         = $request->percent;
                $skill->user_id         = Auth::id();
                $skill->save();

                break;

            case 'cvf': //CV Files

                //dd($request->all());
                //dd(basename($request->file('user_file')->store('public/user-files')));
                if($request->hasFile('user_file')){


                    $file = new UserFiles();
                    $fileName               = basename($request->file('user_file')->store('public/user-files'));
                    $file->file_path        = '/user-files/'.$fileName;
                    $file->file_name        = $request->file_name;
                    //$file->subcategory_id   = UserServices::find($request->service_id)->subcategory_id;
                    $file->user_id          = Auth::id();
                    $file->save();
                }
                //dd($request->user_file);

                break;

            case 'cvl': //CV Languages
                $language = explode(',', $request->language);
                $lang = new CVLanguages();
                $lang->lang_code        = $language[0];
                $lang->language         = $language[1];
                $lang->read             = $request->read ? 1 : 0;
                $lang->understand       = $request->understand ? 1 : 0;
                $lang->speak            = $request->speak ? 1 : 0;
                $lang->user_id          = Auth::id();
                $lang->save();

                break;

            case 'us': //User Services
                $us = new UserServices();
                $us->subcategory_id     = $request->subcategory_id;
                $us->service            = $request->service;
                $us->price_from         = str_replace(' ', '', $request->price_from);
                $us->price_to           = str_replace(' ', '', $request->price_to);
                $us->user_id            = Auth::id();
                $us->save();

                break;

            case 'ur': //User Reviews
                $ur = new UserReviews();
                $ur->review     = $request->review;
                $ur->service_id = $request->service_id;
                $ur->user_id    = Auth::id();
                $ur->save();

                break;

            case 'cvrr': //User Reviews Report

resources/views/admin/cv/form.blade.php
@extends('admin.templates.layout')
@section('content')
    <div class="row">
        <div class="col-12 col-md-12 col-lg-6">
            <div class="card">
                <div class="card-header">
                    <h4>Categorias</h4>
                    <div class="card-header-form">
                        <form>
                            <div class="input-group">
                                {{--<div class="input-group-btn">
                                    <a href="--}}{{--{{ route('admin.users.create') }}--}}{{--" class="btn btn-primary"><i
                                            class="fas fa-plus"> Crear</i>
                                    </a>
                                </div>--}}
                                &nbsp;
                                <input type="text" class="form-control" placeholder="Sección">
                                {!! Form::select('name', $sectionTypes, null , ['class' => 'form-control']) !!}
                                {{--<input type="text" class="form-control" placeholder="Sección">--}}
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-primary">Agregar
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="card-body p-3">
                    <div class="table-responsive">
                        <table class="table table-striped data-table">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Sección</th>
                                <th>Activo</th>
                                <th>Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($sections as $section)
                                    <tr>
                                        <td class="p-0 text-center">{{ $section->id }}</td>
                                        <td>{{ $section->section }}</td>
                                        <td>{{ $section->active }}</td>
                                        <td><a href="{{ route('admin.users.edit', [$section->id]) }}" class="btn btn-primary">Editar</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/cv/index.blade.php
@extends('admin.templates.layout')
@section('head')
    {{-- DataTable --}}
    <link href="https://cdn.datatables.net/1.10.17/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection
@section('content')
    <div class="row">
        <div class="col-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4>Categorias</h4>
                    <div class="card-header-form">
                        <form>
                            <div class="input-group">
                                <div class="input-group-btn">
                                    <a href="{{--{{ route('admin.users.create') }}--}}" class="btn btn-primary"><i
                                                class="fas fa-plus"> Crear</i>
                                    </a>
                                </div>
                                &nbsp;
                                <input type="text" class="form-control" placeholder="Search">
                                <div class="input-group-btn">
                                    <button class="btn btn-primary"><i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="card-body p-3">
                    <div class="table-responsive">
                        {{--<input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input">
                        <span class="custom-switch-indicator"></span>--}}
                        <table class="table table-striped data-table">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Categoría</th>
                                <th>Creado</th>
                                <th>Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>

                            {{--@foreach($users as $user)
                                <tr>
                                    <td class="p-0 text-center">{{ $user->id }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->cell_phone }}</td>
                                    <td>{{ $user->born_date }}</td>
                                    <td>{{ $user->created_at }}</td>
                                    <td>{{ $user->updated_at }}</td>
                                    <td><a href="{{ route('admin.users.edit', [$user->id]) }}" class="btn btn-primary">Editar</a>
                                    </td>
                                </tr>
                            @endforeach--}}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <!-- Page Specific JS File -->
{{--<script src="/assets/bundles/apexcharts/apexcharts.min.js"></script>

    <!-- Template JS File -->
    <script src="/assets/js/scripts.js"></script>
    <!-- Custom JS File -->
    <script src="/assets/js/custom.js"></script>--}}
    <script src="/admin/assets/js/page/forms-advanced-forms.js"></script>

 {{--DataTable--}}

    <script src="https://cdn.datatables.net/1.10.17/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script>
        function submit() {
            console.log($('#usuariosForm'))
        }

        $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var table = $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{--{{ route('admin.users.index') }}--}}",
                language: {
                    url:      "/admin/assets/json/DataTableSpanish.json",
                },
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                    {data: 'name', name: 'name'},
                    {data: 'email', name: 'email'},
                    {data: 'roles', name: 'roles'},
                    {data: 'created_at', name: 'created_at'},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            })
        })

    </script>
@endsection