routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * WEB
 */

Route::get('/', 'Web\HomeController@index')->name('web.index');
Route::get('/referred/{code}', 'Web\UserController@referred')->name('web.referred');

Route::group(['middleware' => ['auth', 'notifications', 'CVChecked']], function () {


    Route::get('/home', 'Web\HomeController@home')->name('web.home');
    Route::get('/suscription/{plan}/checkout', 'Web\SuscriptionControllers@checkout')->name('web.suscription.checkout')->middleware('verified');;
    Route::get('/suscription/{plan}/finish', 'Web\SuscriptionControllers@checkoutFinish')->name('web.suscription.finish')->middleware('verified');;

    //Route::get('/notifications/add', 'Web\NotificationsControllers@add')->name('web.notifications.add');

    /*
     * Events
     */
    Route::get('/events/{event?}', 'Web\EventsControllers@event')->name('web.events');
    Route::get('/category', function (){
        return view('web.category-page');
    });
    /*
     * Profile
     */
    Route::get('/profile/{user}', 'Web\UserController@profile')->name('web.profile')->middleware('verified');
    Route::post('/profile/cv/store', 'Web\CVController@store')->name('web.profile.cv.store')->middleware('verified');
    Route::post('/profile/cv/additem', 'Web\CVController@addItem')->name('web.profile.cv.additem')->middleware('verified');
    //Route::match(['get', 'post'], '/profile/cv/additem', 'Web\CVController@addItem')->middleware('verified');


    Route::get('/profile/cv/delete/{fromTable}/{item}', 'Web\CVController@deleteItem')->name('web.profile.cv.deleteitem')->middleware('verified');
    Route::post('/profile/avatar/update', 'Web\CVController@avatarUpdate')->name('web.profile.avatar.update')->middleware('verified');

    /*
     * Search
     */
    Route::get('/search/{subcategory?}', 'Web\SearchController@index')->name('web.search')->middleware('verified');;
    Route::get('/home/search', 'Web\SearchController@homeSearch')->name('web.home.search')->middleware('verified');;
    //Route::get('/search/get', 'Web\SearchController@search')->name('web.search.get');
    Route::get('/search/subcategories/{id}', 'Web\SearchController@subcategories')->name('web.search.subcategories')->middleware('verified');;

});

/*
 * ADMIN
 */
Route::group(['middleware' => ['auth', 'role:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/email', function (){
        return view('web.email.verify');
    });

    Route::get('/dashboard', 'Admin\HomeController@index')->name('dashboard');

    Route::resource('users', 'Admin\UsersController');

    Route::resource('events', 'Admin\EventsController',['only' => ['index', 'store', 'create', 'update', 'show', 'edit']]);
    Route::get('events/destroy/{id}', 'Admin\EventsController@destroy')->name('events.destroy');

    Route::resource('categories', 'Admin\CategoriesController',['only' => ['index', 'store', 'create', 'update', 'show', 'edit']]);
    Route::get('categories/destroy/{id}', 'Admin\CategoriesController@destroy')->name('categories.destroy');

    Route::resource('subcategories', 'Admin\SubCategoriesController',['only' => ['index', 'store', 'create', 'update', 'show', 'edit']]);
    Route::get('subcategories/destroy/{id}', 'Admin\SubCategoriesController@destroy')->name('subcategories.destroy');;

    Route::resource('memberships', 'Admin\MembershipsController');

    Route::resource('plans', 'Admin\PlansController');

    Route::resource('reviews', 'Admin\ReviewsController',['only' => ['index', 'store', 'create', 'update', 'show', 'edit']]);
    Route::get('reviews/destroy/{id}', 'Admin\ReviewsController@destroy')->name('reviews.destroy');

    /*Route::get('users', function () {
        // Matches The "/admin/users" URL
    });*/
});




Route::group([/*'middleware' => ['auth', 'role:admin'], */'prefix' => 'admin', 'as' => 'admin.'], function () {





});







/**
 * DESIGN
 */

/*Route::get('/', function (){
   return view('web.landing');
})->name('web');;*/

/*   return view('web.home');
});*/


/*Route::get('/home', function (){
    return view('web.landing');
 })->name('web.landing');*/

/*Route::get('/search', function (){
    return view('web.search');
})->name('web.search');*/

/**
 * EVENTOS
 */
Route::get('/eventos', function (){
    return view('web.eventos');
})->name('web.eventos');


/*
 * ORGANIZADOR
 */
/*Route::get('/organizador', function (){
    return view('web.organizador');
})->name('web.organizador');*/


//Auth::routes();

Auth::routes(['verify' => true]);

Route::get('/register/{role?}', 'Auth\RegisterController@showRegistrationForm')
    ->name('register');

Route::get('/login/{provider}', 'Auth\LoginController@redirectToProvider')
    ->name('social.login');
Route::get('/login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')
    ->name('social.callback');



/*Route::get('/', 'HomeController@index')->name('home');*/

/*Route::get('/search-category', function (){
    return view('web.category-page');
});*/

Route::get('/preguntas-frecuentes', function (){
    return view('web.preguntas');
})->name('web.preguntas');


/*Route::get('/checkout', function (){
    return view('web.checkout');
})->name('web.checkout');*/

app/Http/Livewire/Web/Profile/WizardCv.php
<?php

namespace App\Http\Livewire\Web\Profile;

use App\Categories;
use App\CVAcademicInformation;
use App\CVInformation;
use App\CVWorkExperience;
use App\Days;
use App\Helpers\Message;
use App\UserDays;
use App\UserInformation;
use App\UserServices;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Livewire\Component;
use Livewire\WithFileUploads;

class WizardCv extends Component
{
    use WithFileUploads;

    public $currentStep = 1, $subcategories, $days;

    /*
     * STEP 1
     */
    public $about;

    /*
     * STEP 2
     */
    public $subcategory_id_main;

    /*
     * STEP 3
     */
    public $subcategory_id, $service, $price_from, $price_to;

    /*
     * STEP 4
     */
    public $pregunta, $work_status, $business, $antiquity, $current_work;

    /*
     * STEP 5
     */
    public $day, $hour_from, $hour_to;

    /*
     * STEP 6
     */
    public $institution, $institution_1, $institution_2, $from_year, $from_year_1, $from_year_2, $to_year, $to_year_1, $to_year_2, $title, $title_1, $title_2, $academic_file, $academic_file_1, $academic_file_2;

    /*
     * STEP 7
     */
    public $latitud, $longitud, $city_name, $city_place_id;

   /* protected $rules = [
        'about' => 'required',
        //'email' => 'required|email',
    ];*/

    /*protected $messages = [
        'email.required' => 'The Email Address cannot be empty.',
        'email.email' => 'The Email Address format is not valid.',
    ];*/

    protected $validationAttributes = [
        'about' => 'sobre ti'
    ];

    public function firstStep()
    {


        /*$this->validate([
            'about' => 'required',
        ]);*/

        $this->currentStep = 2;
    }

    public function secondStep()
    {
        /*$this->validate([
            'subcategory_id_main' => 'required',
        ]);*/

        $this->currentStep = 3;
    }

    public function thirdStep(/*$field*/)
    {
        //dd($field);
       /* $this->validate([
            'subcategory_id' => 'required',
            'service'       => 'required',
            'price_from'     => 'required',
            'price_to'       => 'required',
        ]);*/

        $this->currentStep = 4;
    }

    public function FourthStep()
    {
        /*$this->validate([
            'pregunta'      => 'required',
            'business'      => 'required_if:pregunta,=,1',
            'antique'       => 'required_if:pregunta,=,1',
            'current_work'  => 'required_if:pregunta,=,1',
            'work_status'  => 'required_if:pregunta,=,2',
        ]);*/

        $this->currentStep = 5;
    }

    public function FifthStep()
    {
       /* $this->validate([
            'day'           => 'required',
            'hour_from'     => 'required',
            'hour_to'       => 'required'
        ]);*/

        $this->currentStep = 6;
    }

    public function SixthStep()
    {

        //session()->flash('notifications', Message::message('AA', 'BB', 'success'));
        $this->validate([
            'institution' => 'required_with:from_year,to_year, title',
            'from_year' => 'required_with:institution,to_year, title, from_year',
            'to_year' => 'required_with:from_year,to_year, title, institution',
            'title' => 'required_with:from_year,to_year, institution',

            'institution_1' => 'required_with:from_year_1,to_year_1, title_1',
            'from_year_1' => 'required_with:institution_1,to_year_1, title_1, from_year_1',
            'to_year_1' => 'required_with:from_year_1,to_year_1, title_1, institution_1',
            'title_1' => 'required_with:from_year_1,to_year_1, institution_1',

            'institution_2' => 'required_with:from_year_2,to_year_2, title_2',
            'from_year_2' => 'required_with:institution_2,to_year_2, title_2, from_year_2',
            'to_year_2' => 'required_with:from_year_2,to_year_2, title_2, institution_2',
            'title_2' => 'required_with:from_year_2,to_year_2, institution_2',
        ]);

        $this->currentStep = 7;
    }

    /*public function mount($post)
    {
        dd($post);
        //$this->latitud = $post->latitud;
        //$this->content = $post->content;
    }*/

    public function SeventhStep()
    {
        //dd(str_replace(' ', '', $this->price_from));
        //dd($this->latitud);
        //dd($latitud);
        /*$this->validate([
            'subcategory_id_main' => 'required',
        ]);*/
        try {
            Log::info('Begin');
            DB::beginTransaction();

            $userinfo = UserInformation::where('user_id', Auth::id())->first();
            $userinfo->latitud          = $this->latitud;
            $userinfo->longitud         = $this->longitud;
            $userinfo->city_name        = $this->city_name;
            $userinfo->city_place_id    = $this->city_place_id;
            $userinfo->save();

            $cvinformation = CVInformation::firstOrNew(['user_id' => Auth::id()]);
            $cvinformation->about           = $this->about;
            $cvinformation->subcategory_id  = $this->subcategory_id_main;
            $cvinformation->work_status     = $this->work_status;
            $cvinformation->user_id         = Auth::id();
            $cvinformation->save();

            if ($this->business){
                Log::info('Work');
                $workexperience = new CVWorkExperience();
                $workexperience->business       = $this->business;
                $workexperience->current_work   = $this->current_work ? 1 : 0;
                $workexperience->antiquity      = $this->antiquity;
                $workexperience->user_id        = Auth::id();
                $workexperience->save();
            }

            if ($this->day == 'lv'){
                $days = Days::whereIn('id', [2,3,4,5,6])->get();
                foreach ($days as $d) {
                    $userdays = new UserDays();
                    $userdays->user_id = Auth::id();
                    $userdays->day_id = $d->id;
                    $userdays->hour_from = $this->hour_from;
                    $userdays->hour_to = $this->hour_to;
                    $userdays->save();
                }
            }else{
                $userdays = new UserDays();
                $userdays->user_id = Auth::id();
                $userdays->day_id = $this->day;
                $userdays->hour_from = $this->hour_from;
                $userdays->hour_to = $this->hour_to;
                $userdays->save();
            }


            if ($this->service){

                $services = new UserServices();
                $services->subcategory_id   = $this->subcategory_id;
                $services->service          = $this->service;
                $services->price_from       = str_replace(' ', '', $this->price_from);
                $services->price_to         = str_replace(' ', '', $this->price_to);
                $services->user_id          = Auth::id();;
                $services->save();
            }

            if ($this->institution && $this->from_year && $this->to_year && $this->title) {
                $academic = new CVAcademicInformation();
                $academic->institution = $this->institution;
                $academic->from_year = $this->from_year;
                $academic->to_year = $this->to_year;
                $academic->title = $this->title;
                $academic->user_id = Auth::id();
                $academic->save();

                if ($this->academic_file){
                    $academic->academic_file = basename($this->academic_file->store('public/user-files'));
                    $academic->save();
                }
            }

            if ($this->institution_1 && $this->from_year_1 && $this->to_year_1 && $this->title_1) {
                $academic = new CVAcademicInformation();
                $academic->institution = $this->institution_1;
                $academic->from_year = $this->from_year_1;
                $academic->to_year = $this->to_year_1;
                $academic->title = $this->title_1;
                $academic->user_id = Auth::id();
                $academic->save();
            }

            if ($this->institution_2 && $this->from_year_2 && $this->to_year_2 && $this->title_2) {
                $academic = new CVAcademicInformation();
                $academic->institution = $this->institution_2;
                $academic->from_year = $this->from_year_2;
                $academic->to_year = $this->to_year_2;
                $academic->title = $this->title_2;
                $academic->user_id = Auth::id();
                $academic->save();
            }

            DB::commit();
            //Session::put('notifications', Message::message('A','B','success'));
            //session('notifications') =
            Log::info('Commit');

            session()->flash('notifications', Message::message('Información guardada', 'Se ha guardado tu información correctamente', 'success'));

            return redirect()->route('web.profile', Auth::user()->slug);

        }catch (\Exception $e){
            DB::rollBack();
            session()->flash('notifications', Message::message('Error al guardar', 'No se pudo guardar tu información', 'danger'));
            Log::info('Rollback: '.$e->getMessage() );

        }

        /*$cvinformation = CVInformation::firstOrNew(['user_id' => Auth::id()]);
        $cvinformation->about           = $this->about;
        $cvinformation->subcategory_id  = $this->subcategory_id_main;
        $cvinformation->work_status     = $this->work_status;
        $cvinformation->user_id         = Auth::id();
        $cvinformation->save();

        if (!$this->work_status){
            $workexperience = new CVWorkExperience();
            $workexperience->business       = $this->business;
            $workexperience->current_work   = $this->current_work ? 1 : 0;
            $workexperience->antiquity      = $this->antiquity;

resources/views/web/profile/modals/modalAddComment.blade.php
<div class="modal" id="comentariosModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">

                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-6">
                        <video autoplay width="100%"
                               style="-webkit-mask-box-image: url('https://freepik.cdnpk.net/img/video/karma/mask.svg'); mask-image: url('');">
                            <source src="https://freepik.cdnpk.net/img/video/karma/video.mp4"
                                    type="video/mp4">
                        </video>
                    </div>
                    <div class="col-sm-6">
                        <h2>Recuerda que cada comentario nos ayuda a mejorar.</h2>
                        {!! Form::open(['route' => 'web.profile.cv.additem', 'method' => 'post']) !!}
                        <input type="hidden" name="data_from" value="ur">
                        <div class="form-group">
                            <label for="email">Selecciona el servicio</label>
                            {!! Form::select('service_id', $user->services->pluck('service', 'id') , null , ['class' => 'custom-select', 'placeholder' => 'Elige un servicio', 'required' => true]) !!}
                        </div>
                        <div class="form-group">
                            <label for="pwd">Escribe brevemente el comentario</label>
                            {!! Form::textarea('review', '', ['class' => 'form-control', 'row' => 5, 'placeholder' => 'Comentario', 'required' => true]) !!}
                        </div>
                        <button type="submit" class="btn btn-info float-right btn-round">
                            Comentar
                        </button>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/web/profile/modals/modalAddFile.blade.php
<div class="modal" id="addFile">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <div class="row">

                    <div class="col-md-8 offset-2">
                        {!! Form::open(['route' => 'web.profile.cv.additem', 'method' => 'post', 'files' => true]) !!}
                        <input type="hidden" name="data_from" value="cvf">
                        <div class="form-group">
                            <label for="email">Selecciona el servicio</label>
                            {!! Form::select('service_id', $user->services->pluck('service', 'id') , null , [
                                'class' => 'custom-select',
                                'placeholder' => 'Elige un servicio']) !!}
                        </div>

                        <input type="file" multiple class="form-control" name="user_file" accept="image/x-png,image/jpg,image/jpeg">
                        <br>
                        <button type="submit" class="btn btn-info float-right btn-round">
                            Guardar datos
                        </button>
                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/web/profile/modals/modalAddHability.blade.php
<div class="modal" id="addHability">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <div class="row">
                    
                    <div class="col-md-8 offset-2">
                        {!! Form::open(['route' => 'web.profile.cv.additem', 'method' => 'post']) !!}
                        <input type="hidden" name="data_from" value="cvs">
                        <div class="form-group">
                            <label for="email">Habilidad/ Conocimiento</label>
                            <input type="text" name="skill" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="email">Nivel</label><br>
                            <div
                                class="custom-control custom-radio custom-control-inline">
                                <input type="radio" class="custom-control-input"
                                       id="basico" name="percent" value="25">
                                <label class="custom-control-label"
                                       for="basico">Básico</label>
                            </div>
                            <div
                                class="custom-control custom-radio custom-control-inline">
                                <input type="radio" class="custom-control-input"
                                       id="intermedio" name="percent" value="50">
                                <label class="custom-control-label" for="intermedio">Intermedio</label>
                            </div>
                            <div
                                class="custom-control custom-radio custom-control-inline">
                                <input type="radio" class="custom-control-input"
                                       id="avanzado" name="percent" value="75">
                                <label class="custom-control-label"
                                       for="avanzado">Avanzado</label>
                            </div>
                            <div
                                class="custom-control custom-radio custom-control-inline">
                                <input type="radio" class="custom-control-input"
                                       id="experto" name="percent" value="100">
                                <label class="custom-control-label"
                                       for="experto">Experto</label>
                            </div>
                        </div>
                        <button type="submit"
                                class="btn btn-info float-right btn-round">Guardar datos
                        </button>
                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/web/profile/modals/modalAddLanguages.blade.php
<div class="modal" id="addLanguages">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div class="row">
                    
                    <div class="col-md-8 offset-2">
                        {!! Form::open(['route' => 'web.profile.cv.additem', 'method' => 'post']) !!}
                        <input type="hidden" name="data_from" value="cvl">
                        <div class="form-group">
                            <label for="email">Selecione el idioma</label>
                            <select name="language" class="custom-select">
                                <option selected>General</option>
                                <option value="ES,Español"><img
                                        src="/web/assets/img/flags/ES.png">Español
                                </option>
                                <option value="US,Inglés"><img
                                        src="/web/assets/img/flags/US.png">Ingles
                                </option>
                                <option value="BR,Portugués"><img
                                        src="/web/assets/img/flags/BR.png">Portugues
                                </option>
                                <option value="DE,Alemán"><img
                                        src="/web/assets/img/flags/DE.png">Aleman
                                </option>
                                <option value="CN,Chino"><img
                                        src="/web/assets/img/flags/CN.png">Chino
                                </option>
                                <option value="PY,Guarani"><img
                                        src="/web/assets/img/flags/PY.png">Guaraní
                                </option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="">Nivel de lenguaje</label>
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input"
                                       id="read" name="read">
                                <label class="custom-control-label"
                                       for="read">Lee</label>
                            </div>
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input"
                                       id="understand" name="understand">
                                <label class="custom-control-label" for="understand">Comprende</label>
                            </div>
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input"
                                       id="speak" name="speak">
                                <label class="custom-control-label"
                                       for="speak">Habla</label>
                            </div>
                        </div>
                        <button type="submit"
                                class="btn btn-info float-right btn-round">Guardar datos
                        </button>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/web/profile/modals/modalAddSchedule.blade.php
<div class="modal" id="newSchedule">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                {!! Form::open(['route' => 'web.profile.cv.additem', 'method' => 'post']) !!}
                <input type="hidden" name="data_from" value="cvsch">
                <div id="schedules_id" class="form-inline">
                    <div class="form-group  mx-sm-3 mb-2">
                        <label for="inputServicio" class="sr-only">Día</label>
                        {!! Form::select('day', $days , null , ['class' => 'form-control', 'placeholder' => 'Elige el día']) !!}
                    </div>
                    <div class="form-group mx-sm-3 mb-2">
                        <label for="inputPrecioDesde" class="sr-only">Desde</label>
                        <input type="time" class="form-control" name="hour_from"
                               placeholder="Desde">
                    </div>
                    <div class="form-group mx-sm-3 mb-2">
                        <label for="inputPrecioHasta" class="sr-only">Hasta</label>
                        <input type="time" class="form-control" name="hour_to"
                               placeholder="Hasta">
                    </div>
                </div>
                <button class="btn btn-info btn-lg btn-round btn-block">
                    Guardar Datos
                </button>
                {!! Form::close() !!}
            </div>


        </div>
    </div>
</div>

resources/views/web/profile/modals/modalAddServices.blade.php
<div class="modal" id="addService">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div class="row">
                   
                    <div class="col-md-8 offset-2">
                        {!! Form::open(['route' => 'web.profile.cv.additem', 'method' => 'post']) !!}
                        <input type="hidden" name="data_from" value="us">
                        <div class="form-group">
                            <label for="email">Selecciona la subcategoría</label>
                            {!! Form::select('subcategory_id', $subcategories , null , ['class' => 'custom-select select-picker', 'placeholder' => 'Selecciona la subcategoría']) !!}
                        </div>

                        <div class="form-group">
                            <label for="service">Servicio</label>
                            <input type="text" id="service" name="service"
                                   class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="price">Precio desde</label>
                            <input type="text" id="price_from" name="price_from"
                                   class="form-control isnumber">
                        </div>
                        <div class="form-group">
                            <label for="price">Precio hasta</label>
                            <input type="text" id="price_to" name="price_to"
                                   class="form-control isnumber">
                        </div>
                        <button type="submit"
                                class="btn btn-info float-right btn-round">Guardar datos
                        </button>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/web/profile/modals/modalCreateCV.blade.php
<div class="modal" id="crearCV">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            
            <!-- Modal body -->
            <div class="modal-body">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-12">
                        <div class="tab-content" id="main_form">
                            <livewire:web.profile.wizard-cv :subcategories="$subcategories">
                                <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>